### ISSUE TITLE
bmlt 3.0.0 gives a 500 error

### ISSUE THREAD

**Issue by paulnagle** [bmlt-enabled/bmlt-root-server#861] opened 2023-01-14 09:56 UTC
Hey,
  I tried out the new version 3, but I got a server error 500 page when I browsed to the main_server page..  Here is the first error from the laravel .log file

```[2023-01-14 08:50:10] production.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `na_sessions` add primary key `na_sessions_id_primary`(`id`)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `na_sessions` add primary key `na_sessions_id_primary`(`id`)) at /home/nasouth0/public_html/bmlt/main_server/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)```

Full laravel.log file. 
[laravel (1).log](https://github.com/bmlt-enabled/bmlt-root-server/files/10417070/laravel.1.log)

Here is what the bmlt 2.16 DB looks like
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/3714999/212466148-63be8571-9358-4eab-bb23-eea7d4fd6cc3.png">

The bmlt 3 DB was created, but is still empty. 

From googling it looks like this is related to the mysql innodb issue in https://github.com/bmlt-enabled/bmlt-root-server/issues/860 .  I've reverted back to bmlt 2.16, so theres no rush, but any suggestions for me would be appreciated.

**Comment by jbraswell** [comment] 2023-01-14 14:51
Hi Paul. This is the same error Australia got. It was caused by the storage engine (InnoDB) not being specified when the tables are created, so the issue only exists on hosts where InnoDB is not the default storage engine. It is fixed in 3.0.1, but first you'll need to drop two tables that were created.

So... first run these sql statements

```
DROP TABLE na_migrations;
DROP TABLE na_sessions;
```

And then upgrade to 3.0.1, which has the fix.

**Closed by jbraswell** 2023-01-14 14:51 UTC
