### ISSUE TITLE
New version gives 500 | Server Error

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/bmlt-root-server#860] opened 2023-01-14 05:42 UTC
After doing the 3 card monty rename the new version gives a 500 error.
switch back and the old version works.
My workflow is 
1. download the new version
2. Extract the contents
3. rename main_server to "main_server_new"
4. recompress main_server_new 
5. Upload the zip file to public_html
6. extract the main_server_new zip
7. three card monty rename
8. check the root server and it fails

Initally tried using PHP 8.0 and it failed.  So I changed to 8.1 and it still gives the same error

**Comment by jbraswell** [comment] 2023-01-14 05:44
Is there a log file in main_server_new/storage/logs?

**Comment by jbraswell** [comment] 2023-01-14 05:48
If there are no log files in storage/logs, I'll probably need you to give me access to the host.

**Comment by brustar64** [comment] 2023-01-14 05:52
> If there are no log files in storage/logs, I'll probably need you to give me access to the host.

[laravel.log](https://github.com/bmlt-enabled/bmlt-root-server/files/10416752/laravel.log)

**Comment by jbraswell** [comment] 2023-01-14 05:53
Based on the contents of the file, I am going to need access to your host to get this fixed. Will you reach out to me on slack or facebook messenger?

**Comment by jbraswell** [comment] 2023-01-14 06:43
It looks like this problem is caused by the host's default mysql storage engine being MyISAM instead of InnoDB. The first migration fails to create a primary key constraint on the id column, which is a varchar(255) column. We've opened a ticket with the web host to change the default storage engine.

No data is corrupted, because luckily, it failed on the very first migration.

**Comment by jbraswell** [comment] 2023-01-14 14:51
Fixed in 3.0.1.

**Closed by jbraswell** 2023-01-14 14:51 UTC
